# Generated by Django 5.0.4 on 2026-05-12 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UPA',
                'verbose_name_plural': 'UPAs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilRecepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('upa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionistas', to='filas.upa')),
            ],
            options={
                'verbose_name': 'Recepcionista',
                'verbose_name_plural': 'Recepcionistas',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('vacina', 'Vacina'), ('curativo', 'Curativo'), ('farmacia', 'Farmácia'), ('prioridade', 'Prioridade')], max_length=20)),
                ('senha', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('atendido', 'Atendido'), ('ausente', 'Ausente')], default='aguardando', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('upa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='filas.upa')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['criado_em'],
            },
        ),
    ]
