# Generated by Django 5.0.4 on 2026-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='motivo_prioridade',
            field=models.CharField(blank=True, choices=[('idoso', 'Idoso (60+)'), ('gestante', 'Gestante'), ('deficiencia', 'Pessoa com deficiência'), ('crianca', 'Criança (menor de 5 anos)'), ('outro', 'Outro')], max_length=20),
        ),
    ]
