# Generated by Django 5.0.4 on 2026-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0002_atendimento_motivo_prioridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-prioridade', 'criado_em'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
        migrations.AddField(
            model_name='atendimento',
            name='prioridade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('vacina', 'Vacina'), ('curativo', 'Curativo'), ('farmacia', 'Farmácia')], max_length=20),
        ),
    ]
