# Generated by Django 5.0.4 on 2026-05-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0004_perfildiretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildiretor',
            name='upa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diretores', to='filas.upa'),
            preserve_default=False,
        ),
    ]
