# Generated by Django 5.0.4 on 2026-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0005_perfildiretor_upa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='origem',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], default='online', max_length=10),
        ),
    ]
