# Generated by Django 5.0.4 on 2026-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0006_atendimento_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('nao_compareceu', 'Não compareceu'), ('atendido', 'Atendido'), ('ausente', 'Ausente')], default='aguardando', max_length=20),
        ),
    ]
